[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
rustflags = [
    "-C", "link-arg=-Wl,--no-warn-rwx-segments",
    "-C", "link-arg=--ldproxy-linker=.embuild/espressif/tools/riscv32-esp-elf/esp-12.2.0_20230208/riscv32-esp-elf/bin/riscv32-esp-elf-gcc",
]

[env]
ESP_IDF_VERSION = "v5.1.4"
MCU = "esp32c3"

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
