[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor --partition-table ../../partitions.csv"

[env]
ESP_IDF_SYS_ROOT_CRATE = "blackbox"
MCU = "esp32c3"

[unstable]
build-std = ["std", "panic_abort"]
